spring.application.name=driveme

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://maglev.proxy.rlwy.net:23328/railway}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:zFPisViUhxnwKMHiFTNRMvaiNdWEhiZF}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

bedrock.agent.id=${BEDROCK_AGENT_ID}
bedrock.agent.alias=${BEDROCK_AGENT_ALIAS}
